Ratings/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
    url(r'^add_question','main.views.add_question', name='add_question'),
]

main/urls.py
from . import views
from django.conf.urls import url
app_name ='main'
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^adding', views.addingQuestion, name='addingQuestion'),
]

main/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    views = models.PositiveIntegerField(_('Hits'), default=0)
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - timezone.timedelta(days=1)
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import Question, Choice
from django.template import RequestContext, loader
from django.utils import timezone
from django.db.models import F

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'main/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.views = question.views +1
    question.save
    return render(request, 'main/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'main/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'main/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('main:results', args=(question.id,)))

def add_question(request):
    return render(request, 'main/add_question.html')

def addingQuestion(request):
    if request.method == 'POST':
        question = request.POST.get('text')
        date = timezone.now()
        u = Question(question_text=question,pub_date=date)
        u.save()
        for x in range (1,7):
            string = str(x)
            choice = request.POST.get(string)
            if(choice!=""):
                new = Choice(question=u,choice_text=choice)
                new.save()
    return HttpResponseRedirect(reverse('main:index'))

templates/main/add_question.html
<!DOCTYPE html>
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}" />
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fill the form</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
</head>
<body>
    <form action="{% url 'main:addingQuestion' %}" method="post" id="form">
        {% csrf_token %}
        Fill in your question: <input type="text" id="text" name="text"> <br>
    Select how many choices you want:
    <select id = "myselect" class="target">
        {% for i in "xxxxxx" %}
            <option value="{{ forloop.counter }}" selected="selected"> {{ forloop.counter }}</option>
        {% endfor %}
    </select>
    <br>
        {% for i in "xxxxxx" %}
            <input type="" id="{{ forloop.counter }}" name="{{ forloop.counter }}"> <br>
        {% endfor %}
    <input type="submit" value="im done man" />
    </form>
</body>
</html>

<script>
    $( ".target" ).change(function() {
    var sel = document.forms['form'].elements['myselect'];
    var val = sel.value;
        for(i=1; i<7; i++)
        {
            if(i>val)
                document.getElementById(i).setAttribute("type","hidden");
            else
                document.getElementById(i).setAttribute("type","");
        }
});
</script>

templates/main/detail.html
<!DOCTYPE html>
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}" />
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'main:vote' question.id %}" method="post">
    {% csrf_token %}
    {% if question.choice_set.all %}
        {% for choice in question.choice_set.all %}
            <div class="radioSet">
           <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
            </div>
            <br />
        {% endfor %}
        <input type="submit" value="Vote" />
    {% else %}
        <p> No choices available for now</p>
        <a href="/">Home</a>
    {% endif %}
    </form>
</body>
</html>

templates/main/index.html
<!DOCTYPE html>
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}" />
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    {% if latest_question_list %}
        <ol class="questions">
        {% for question in latest_question_list %}
            <nav class="question">
            <li><a class="cl-effect-13" href={{ question.id }}>{{ question.question_text }}</a></li> Date: {{ question.pub_date }}
            <a class="button" href={{ question.id }}/results>Results</a>
            </nav>
        {% endfor %}
        </ol>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
    <a class="button" href="/add_question"> Add new</a>
</body>
</html>

templates/main/results.html
<!DOCTYPE html>
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}" />
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Results</title>
</head>
<body>
<nav class="menu">
    <ul>
    <li><a href="{% url 'main:detail' question.id %}">Vote</a></li>
    <li><a href="/">Home</a></li>
    </ul>
</nav>
    <h1>{{ question.question_text }}</h1>
    {% if question.choice_set.all %}

        <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
        </ul>

    {% else %}
        <p>No results to show</p>
    {% endif %}
</body>
</html>